---
# pihole-restricted-22: Restricted blocklist, Primary instance
# Proxmox Node: joseph | LXC ID: 122

profile: restricted
role: primary

# Network IPs
dns_ip: "192.168.1.22"
mgmt_ip: "192.168.5.22"
transfer_ip: "192.168.11.22"
