# ============================================================================
# Pi-hole LXC Module Outputs
# ============================================================================

locals {
  # Build host entries with all required info
  # Uses functional naming (trusted, mgmt, storage) with legacy aliases for compatibility
  all_hosts = {
    for name, inst in var.instances : name => {
      ansible_host = "${name}.lan" # Use .lan hostname for SSH cert auth
      mgmt_ip      = inst.mgmt_ip
      vmid         = inst.vmid
      proxmox_node = inst.node
      # Functional network names
      trusted_ip = inst.dns_ip
      storage_ip = inst.transfer_ip
      # Legacy aliases for backward compatibility
      dns_ip      = inst.dns_ip
      transfer_ip = inst.transfer_ip
      profile     = inst.profile
      role        = inst.role
    }
  }

  # Group hosts by profile
  standard_hosts = {
    for name, inst in var.instances : name => {}
    if inst.profile == "standard"
  }

  restricted_hosts = {
    for name, inst in var.instances : name => {}
    if inst.profile == "restricted"
  }

  # Group hosts by role
  primary_hosts = {
    for name, inst in var.instances : name => {}
    if inst.role == "primary"
  }

  secondary_hosts = {
    for name, inst in var.instances : name => {}
    if inst.role == "secondary"
  }

  # Generate Ansible inventory YAML
  ansible_inventory = {
    all = {
      children = {
        pihole_lxc = {
          vars = {
            ansible_user = "root"
          }
          children = {
            pihole_standard = {
              hosts = local.standard_hosts
            }
            pihole_restricted = {
              hosts = local.restricted_hosts
            }
            pihole_primary = {
              hosts = local.primary_hosts
            }
            pihole_secondary = {
              hosts = local.secondary_hosts
            }
          }
          hosts = local.all_hosts
        }
      }
    }
  }
}

# ============================================================================
# Ansible Inventory Generation
# ============================================================================

resource "local_file" "ansible_inventory" {
  filename        = "${path.module}/../ansible/inventory/${var.env}.yaml"
  content         = "---\n# Auto-generated by Terraform - do not edit manually\n# Regenerate with: terraform apply\n\n${yamlencode(local.ansible_inventory)}"
  file_permission = "0644"
}

# ============================================================================
# Standard Outputs
# ============================================================================

output "instances" {
  description = "Map of created Pi-hole instances"
  value = {
    for name, lxc in proxmox_lxc.pihole : name => {
      vmid        = lxc.vmid
      hostname    = lxc.hostname
      node        = lxc.target_node
      dns_ip      = var.instances[name].dns_ip
      mgmt_ip     = var.instances[name].mgmt_ip
      transfer_ip = var.instances[name].transfer_ip
      profile     = var.instances[name].profile
      role        = var.instances[name].role
    }
  }
}

output "mgmt_ips" {
  description = "Map of hostname to management IP"
  value = {
    for name, config in var.instances : name => config.mgmt_ip
  }
}

output "dns_ips" {
  description = "Map of hostname to DNS IP"
  value = {
    for name, config in var.instances : name => config.dns_ip
  }
}

output "transfer_ips" {
  description = "Map of hostname to transfer/storage IP"
  value = {
    for name, config in var.instances : name => config.transfer_ip
  }
}

output "primary_instances" {
  description = "Primary Pi-hole instances (for nebula-sync source)"
  value = {
    for name, config in var.instances : name => config.mgmt_ip
    if config.role == "primary"
  }
}

output "secondary_instances" {
  description = "Secondary Pi-hole instances (for nebula-sync target)"
  value = {
    for name, config in var.instances : name => {
      mgmt_ip     = config.mgmt_ip
      transfer_ip = config.transfer_ip
      profile     = config.profile
    }
    if config.role == "secondary"
  }
}

output "ansible_inventory_path" {
  description = "Path to generated Ansible inventory file"
  value       = local_file.ansible_inventory.filename
}

# ============================================================================
# DNS CNAME Entries (.lan layer for macOS resolver compatibility)
# ============================================================================

output "cname_entries" {
  description = "CNAME entries for .lan layer and bare names"
  value = merge(
    # .lan → .trusted (DNS queries via trusted network)
    { for name, config in var.instances : "${name}.lan" => "${name}.trusted" },
    # bare → .lan (convenience)
    { for name, config in var.instances : name => "${name}.lan" }
  )
}
